import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Navbar from '@/components/Layout/Navbar/Navbar';
import Sidebar from '@/components/Layout/Sidebar/Sidebar';
import Footer from '@/components/Layout/Footer/Footer';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Velocitor Helpdesk',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Make checkbox checked by default
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${roboto.className}`}>
          <div className="flex min-h-screen">
            <input type="checkbox" id="sidebar-toggle" className="hidden" />
            <Sidebar />
            <div className="flex min-h-screen min-w-0 flex-1 flex-col">
              <Navbar />
              <div className="flex flex-1 bg-slate-200 p-4">
                <div className="max-h-[calc(100vh-8rem)] flex-1 overflow-auto rounded bg-white p-4">
                  {children}
                </div>
              </div>
              <Footer />
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
